@startuml

[Infrastructure] #Aqua
[Shared]
note left of Shared : XxxSupport, Utils

package "model package" {
   [Model] <<Domain>>
   [Repository] <<Domain>>
   [Factory] <<Domain>>
}
package "Logic Layer" {
   [Service] <<Domain>>
   [Event] <<Domain>>
   [Policy] <<Domain>>
   [Application]
   note right of Application : open service\nimplementation and deploy
}

package "SOA Client" {
   [XxxClient] #99FF99
   [XxxClient] -> [PublishedService]
   note right of PublishedService : models, open service api
}

package "App Layer" {
    [WebApp] <<App>>
    [MobileBackend] <<App>>
    [Interface] <<App>>
    [MobileApp] <<App>>
}

[Shared] --> [Infrastructure]
[Repository] --> [Shared]
[Repository] --> [Model]
[Service] -[#0000FF]> [Repository]
[Service] -[#0000FF]> [Policy]
[Policy] -[#0000FF]> [Repository]
[Factory] --> [Model]
[Event] -[#0000FF]> [Service]
[Event] -[#0000FF]> [Repository]
[Application] -[#0000FF]> [Repository]
[Application] -[#0000FF]> [Service]
[Application] -[#0000FF]> [Event]
[Application] -[#0000FF]> [Policy]
[Application] ....> [Infrastructure]
[Application] ....> [Shared]

[PublishedService] ..> [Application]: RPC

[WebApp] ..> [XxxClient]
[Interface] --> [WebApp]
[MobileBackend] ..> [XxxClient]
[MobileApp] --> [MobileBackend]

skinparam component {
  FontSize 13
  BackgroundColor<<Domain>> gold
  BackgroundColor<<App>> DarkKhaki
  FontName Courier
}

@enduml