@startuml


node "Domain Module" {
   package "model package" {
       [Model] <<Domain>>
       [Repository] <<Domain>>
       [Factory] <<Domain>>
    }
   [Service] <<Domain>>
   [Event] <<Domain>>
   [Policy] <<Domain>>
   [Shared]
   note right of Shared : XxxSupport\nWrapper\nSpring Integration

   package "application package" {
        [XxxFacade]
        note left of XxxFacade : facade for external
   }
   package "infrastructure package" {
        [Infrastructure] #Aqua
        [DomainImpl] <<Domain>>
        [DomainImpl] -> [Infrastructure]
   }
}

cloud "App Modules" {
    [WebApp] <<App>>
    [MobileBackend] <<App>>
    [Interface] <<App>>
    [MobileApp] <<App>>
}

[Shared] <-- [DomainImpl]
[XxxFacade] <--- [DomainImpl]
[Repository] ---> [Shared]
[Repository] --> [Model]
[Service] -[#0000FF]> [Repository]
[Service] -[#0000FF]> [Factory]
[Service] -[#0000FF]> [Policy]
[Service] <-[#0000FF]> [Event]
[Policy] -[#0000FF]> [Repository]
[Factory] --> [Model]
[Factory] ---> [Shared]
[Event] -[#0000FF]> [Repository]
[Event] -[#0000FF]> [Factory]
[XxxFacade] -[#0000FF]> [Service]
[XxxFacade] -[#0000FF]> [Event]
[XxxFacade] -[#0000FF]> [Policy]

[WebApp] ...> [XxxFacade]
[Interface] --> [WebApp]
[MobileBackend] ...> [XxxFacade]
[MobileApp] --> [MobileBackend]

skinparam component {
  FontSize 13
  BackgroundColor<<Domain>> gold
  BackgroundColor<<App>> DarkKhaki
  FontName Courier
}

@enduml