@startuml

node "domain module" {
    package "application package" {
       [XxxFacadeImpl] <<Application>>
       note right of XxxFacadeImpl : published service implementation
    }

    package "domain package"  {
       [Model] <<Domain>>
       [Repository] <<Domain>>
       [Factory] <<Domain>>
       [Service] <<Domain>>
       [Event] <<Domain>>
       [Policy] <<Domain>>
    }

    package "infrastructure package" {
       [InfrastructureService] <<Infrastructure>> #Aqua
       [DomainImpl] <<Domain>>
       [DomainImpl] -> [InfrastructureService]
       [DomainImpl] -up-|> [Service]: 逻辑实现
       [DomainImpl] -up-|> [Repository]: 逻辑实现
       [DomainImpl] -up-|> [Factory]: 逻辑实现
       [DomainImpl] -up-|> [Policy]: 逻辑实现
    }
}

package "Client Module" {
    package "Exposed API Module: Facade pattern" {
       [XxxFacade]
       note left of XxxFacade : models\npublished service api
    }
   [XxxClient] #99FF99
   note right of XxxClient : DSL\nSpring Support\nException Handler
   [XxxClient] -left-> [XxxFacade]
}

cloud "App Modules" {
    [WebApp] <<App>>
    [MobileBackend] <<App>>
    [Interface] <<App>>
    [MobileApp] <<App>>
}

[XxxFacadeImpl] <--- [DomainImpl]
[Service] -[#0000FF]> [Factory]
[Service] -[#0000FF]> [Repository]
[Service] .[#0000FF]> [Policy]
[Service] -[#0000FF]up-> [Event]
[Policy] -[#0000FF]> [Repository]
[Repository] -[#0000FF]up-> [Model]
[Factory] -[#0000FF]up-> [Model]

[XxxFacadeImpl] -[#0000FF]--> [Service]
[XxxFacadeImpl] -[#0000FF]--> [Event]
[XxxFacadeImpl] -[#0000FF]--> [Model]
[XxxFacadeImpl] -[#0000FF]--> [Policy]
[XxxFacadeImpl] -[#0000FF]--> [Repository]
[XxxFacadeImpl] -[#0000FF]----> [InfrastructureService]

[XxxFacade] ..> [XxxFacadeImpl]: RPC
[XxxFacade] <|-- [XxxFacadeImpl]: Logic Implement

[WebApp] ..> [XxxClient]
[WebApp] ..> [XxxFacade]
[Interface] --> [WebApp]
[MobileBackend] ..> [XxxClient]
[MobileBackend] ..> [XxxFacade]
[MobileApp] --> [MobileBackend]

skinparam component {
  FontSize 13
  BackgroundColor<<Domain>> gold
  BackgroundColor<<App>> DarkKhaki
  FontName Courier
}

@enduml